### ISSUE TITLE
Repository Code is out of date

### ISSUE THREAD

**Issue by ellenhutchings** [flikore/writerstrail#69]
The code seems to be just a default OpenShift module.

**Comment by vnen** [comment]
I have the intention to release the actual source code soon. I was waiting until it got to a more mature status, but since I can't work much in it anymore, I may just push the code here.

Do you have any interest in contributing to this?

**Comment by ellenhutchings** [comment]
I'd like to see the code for sure, but I've been thinking about experimenting with seeing if I can add an editing mode.

**Comment by vnen** [comment]
Ok, I'm gonna release the code later today. I just have to warn the it is actually a mess and I'm really considering redoing it from scratch (maybe with [Sails.js](sailsjs.org)).
